[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Pascal Friederich <paukul@gmail.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4"
